import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono, Great_Vibes } from "next/font/google";
=======
import { Geist, Geist_Mono } from "next/font/google"; // Import Great_Vibes font
>>>>>>> 77b9d844bbd9cde7852952fc6230d7983316f919
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
<<<<<<< HEAD

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes", 
  subsets: ["latin"],
  weight: "400",
});

=======
>>>>>>> 77b9d844bbd9cde7852952fc6230d7983316f919
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
